spring.application.name=Payment-Service

# 1. Server Configuration
server.port=8084

# 2. Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Hibernate/JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.cloud.openfeign=DEBUG

# 4. Razorpay API Keys (Get these from Razorpay Dashboard)
# TEST Mode sathi 'rzp_test_...' asel ani LIVE sathi 'rzp_live_...'
razorpay.api.key=rzp_test_SXrZL65QmT4jPZ
razorpay.api.secret=hSjYvI6n0rwfj1hqIp1nZN57

# 5. Eureka Client Configuration (Jar API Gateway vaprat asal tar)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# 6. JWT Secret (Jo Auth Service madhe vaprat ahat toch exact ithe pahije)
jwt.secret=SurajJadhavEcommerceMicroservicesJwtSecretKey2026
jwt.expiration=3600000